import Book from "./book.js";

const defaultBooks = [
	new Book("The Hobbit", "J. R. R. Tolkien", true),
	new Book("The Lord of the Rings", "J. R. R. Tolkien", true),
	new Book("The Silmarillion", "J. R. R. Tolkien", true),
	new Book("Middlemarch", "George Eliot"),
	new Book("1984", "George Orwell", true),
	new Book("Animal Farm", "George Orwell", true),
	new Book("Frankenstein", "Mary Shelley"),
	new Book("Jane Eyre", "Charlotte Bronte"),
	new Book("To the Lighthouse", "Virginia Woolf"),
	new Book("Wuthering Heights", "Emily Bronte"),
	new Book("Lord of the Flies", "William Golding", true),
	new Book("Through the Looking Glass", "Lewis Carroll"),
	new Book("Alice in Wonderland", "Lewis Carroll", true),
	new Book("Pride and Prejudice", "Jane Austen"),
	new Book("The Wind in the Willows", "Kenneth Grahame", true),
	new Book("The Lion, the Witch and the Wardrobe", "C.S. Lewis", true),
	new Book("The Horse and his Boy", "C.S. Lewis"),
	new Book("The Magician's Nephew", "C.S. Lewis"),
	new Book("Voyage of the Dawn Treader", "C.S. Lewis"),
	new Book("A Clockwork Orange", "Anthony Burgess"),
	new Book("Prince Caspian", "C.S. Lewis"),
	new Book("The Last Battle", "C.S. Lewis"),
	new Book("The Silver Chair", "C.S. Lewis"),
	new Book("Great Expectations", "Charles Dickens"),
	new Book("Wolf Hall", "Hilary Mantel"),
	new Book("Bring Up The Bodies", "Hilary Mantel"),
	new Book("The Mirror and the Light", "Hilary Mantel"),
	new Book("Gulliver's Travels", "Jonathan Swift"),
	new Book("Persuasion", "Jane Austen"),
	new Book("Vanity Fair", "William Makepeace Thackeray"),
	new Book("Emma", "Jane Austen"),
	new Book("Robinson Crusoe", "Daniel Defoe"),
	new Book("The Remains of the Day", "Kazuo Ishiguro"),
	new Book("Sense and Sensibility", "Jane Austen"),
	new Book("Villette", "Charlotte Bronte"),
	new Book("Mrs Dalloway", "Virginia Woolf"),
	new Book("The End of the Affair", "Graham Greene"),
	new Book("The Woman in White", "Wilkie Collins"),
	new Book("Bleak House", "Charles Dickens"),
	new Book("Possession", "A. S. Byatt"),
];

export default defaultBooks;
